### ISSUE TITLE
search in zh-latn-pinyin returns count of "taxonomy" objects

### ISSUE THREAD

**Issue by berger-n** [BuddhistDigitalResourceCenter/lds-pdi#104] opened 2018-10-12 13:59 UTC
see http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=zh-latn-pinyin&I_LIM=500&L_NAME=%22d%C4%81n%20zh%C5%AB%22
or http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=zh-latn-pinyin&I_LIM=500&L_NAME=%22j%C4%ABng%22:

![image](https://user-images.githubusercontent.com/33383857/46873759-aade0400-ce37-11e8-981f-6ace9d50dd29.png)

**Comment by eroux** [comment] 2018-10-12 14:00
duplicate of #103

**Closed by eroux** 2018-10-12 14:00 UTC
